// Mock dataset of realistic civic incidents and hospitals for CIVICLOOP

export const initialIncidents = [
  {
    id: 'INC-2026-8801',
    type: 'CIVIC',
    category: 'drainage',
    severity: 4,
    title: 'Severe Storm Drain Blockage & Water Stagnation',
    tamilTitle: 'கடுமையான மழைநீர் வடிகால் அடைப்பு மற்றும் நீர் தேக்கம்',
    description: 'Major underground storm drain overflow causing severe flooding near Anna Nagar 2nd Avenue. Mosquito breeding hazard and traffic blockage.',
    tamilDescription: 'அண்ணா நகர் 2வது அவென்யூ அருகில் நிலத்தடி மழைநீர் வடிகால் வழிந்து ஓடி வெள்ளப்பெருக்கு ஏற்பட்டுள்ளது. கொசு உற்பத்தியாகும் அபாயம் உள்ளது.',
    lat: 13.0850,
    long: 80.2101,
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: '2nd Avenue, Anna Nagar, Chennai - 600040',
    department: 'Greater Chennai Corporation (GCC) - Storm Water Drain Dept',
    routingPortal: 'GCC Portal & CM Special Cell',
    truthScore: 96,
    corroboratingSignals: 7,
    status: 'PENDING_ACK',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    unacknowledgedDays: 3,
    retryCount: 0,
    imageUri: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=60'
  },
  {
    id: 'INC-2026-9902',
    type: 'EMERGENCY',
    category: 'accident',
    severity: 5,
    title: 'High-Voltage Transformer Spark & Cable Collapse',
    tamilTitle: 'உயர் அழுத்த டிரான்ஸ்பார்மர் தீப்பொறி மற்றும் கேபிள் வீழ்ச்சி',
    description: 'Live high-voltage cable snapped and fell on main pedestrian walkway near Gandhipuram bus stand. High risk of electrocution!',
    tamilDescription: 'காந்திபுரம் பேருந்து நிலையம் அருகே பிரதான பாதையில் உயர் அழுத்த மின்கம்பி அறுந்து விழுந்தது. மின்சாரம் தாக்கும் கடும் அபாயம்!',
    lat: 11.0168,
    long: 76.9558,
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    address: 'Cross Cut Road, Gandhipuram, Coimbatore - 641012',
    department: 'TNEB Electricity Board & Disaster Rescue Cell',
    routingPortal: 'TNEB Emergency Cell & Fire & Rescue Services',
    truthScore: 99,
    corroboratingSignals: 12,
    status: 'DISPATCHED',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    unacknowledgedDays: 0,
    retryCount: 0,
    imageUri: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=60'
  },
  {
    id: 'INC-2026-7703',
    type: 'CIVIC',
    category: 'water',
    severity: 3,
    title: 'Main Drinking Water Supply Pipeline Burst',
    tamilTitle: 'பிரதான குடிநீர் விநியோக குழாய் உடைப்பு',
    description: 'Over 50,000 liters of clean drinking water spilling continuously into open sewer line near KK Nagar 8th Sector.',
    tamilDescription: 'கே.கே.நகர் 8வது செக்டார் அருகே 50,000 லிட்டருக்கும் அதிகமான குடிநீர் தொடர்ந்து கழிவுநீர் கால்வாயில் வீணாகிறது.',
    lat: 13.0382,
    long: 80.1970,
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: '8th Sector, KK Nagar, Chennai - 600078',
    department: 'Chennai Metro Water Supply & Sewerage Board (CMWSSB)',
    routingPortal: 'CMWSSB Complaint Cell & Area Engineer Office',
    truthScore: 91,
    corroboratingSignals: 4,
    status: 'VERIFIED',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    unacknowledgedDays: 1,
    retryCount: 0,
    imageUri: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=60'
  },
  {
    id: 'INC-2026-6604',
    type: 'WEATHER',
    category: 'weather',
    severity: 4,
    title: 'Coastal Surge & Low-Lying Inundation Threat',
    tamilTitle: 'கடலோர நீர்மட்டம் உயர்வு மற்றும் தாழ்வான பகுதி வெள்ள அபாயம்',
    description: 'Heavy precipitation forecast combined with high tide causing water accumulation near Foreshore Estate beach road.',
    tamilDescription: 'கனமழை எச்சரிக்கையுடன் கடல் அலை சீற்றம் காரணமாக பட்டினப்பாக்கம் அருகே சாலைகளில் நீர் தேங்குகிறது.',
    lat: 13.0298,
    long: 80.2762,
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: 'Foreshore Estate Beach Road, Chennai - 600028',
    department: 'GCC Disaster Cell & Coastal Management Authority',
    routingPortal: 'State Disaster Management Portal',
    truthScore: 94,
    corroboratingSignals: 9,
    status: 'VERIFIED',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    unacknowledgedDays: 0,
    retryCount: 0,
    imageUri: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=600&auto=format&fit=crop&q=60'
  },
  {
    id: 'INC-2026-5505',
    type: 'CIVIC',
    category: 'road',
    severity: 3,
    title: 'Deep Unmarked Road Cave-in on State Highway',
    tamilTitle: 'மாநில நெடுஞ்சாலையில் ஆபத்தான பள்ளம் மற்றும் சாலை சிதைவு',
    description: 'Massive asphalt cave-in near Mattuthavani Bus Terminus causing two-wheeler accidents during night hours.',
    tamilDescription: 'மாட்டுத்தாவணி பேருந்து நிலையம் அருகே சாலையில் ராட்சத பள்ளம் ஏற்பட்டு இருசக்கர வாகன ஓட்டிகள் விபத்துக்குள்ளாகின்றனர்.',
    lat: 9.9400,
    long: 78.1400,
    state: 'Tamil Nadu',
    district: 'Madurai',
    address: 'Melur Main Road, Mattuthavani, Madurai - 625007',
    department: 'State Highways Dept & Madurai Municipal Corporation',
    routingPortal: 'Highways Grievance Portal & Local MLA Contact Cell',
    truthScore: 94,
    corroboratingSignals: 5,
    status: 'SOLVED',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    solvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    unacknowledgedDays: 0,
    retryCount: 1,
    imageUri: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=60'
  }
];

export const mockHospitals = [
  {
    id: 'HOSP-001',
    name: 'Apollo Hospitals Emergency & Trauma Centre',
    tamilName: 'அப்பல்லோ அவசர சிகிச்சை மற்றும் அதிர்ச்சி சிகிச்சை மையம்',
    addressText: 'Greams Lane, Thousand Lights, Chennai - 600006',
    lat: 13.0604,
    long: 80.2496,
    phone: '+91 44 2829 0200',
    emergencyHotline: '1066 / +91 44 2829 3333',
    icuBedsAvailable: 14,
    ambulanceUnits: 6,
    distanceKm: '2.4'
  },
  {
    id: 'HOSP-002',
    name: 'Government General Hospital (RGGGH)',
    tamilName: 'ராஜீவ் காந்தி அரசு பொது மருத்துவமனை',
    addressText: 'EVR Periyar Salai, Park Town, Chennai - 600003',
    lat: 13.0817,
    long: 80.2778,
    phone: '+91 44 2530 5000',
    emergencyHotline: '108 / +91 44 2530 5111',
    icuBedsAvailable: 32,
    ambulanceUnits: 12,
    distanceKm: '1.8'
  },
  {
    id: 'HOSP-003',
    name: 'KMCH Emergency Medical Centre (Coimbatore)',
    tamilName: 'கே.எம்.சி.ஹெச் அவசர மருத்துவ மையம் (கோவை)',
    addressText: 'Avinashi Road, Civil Aerodrome Post, Coimbatore - 641014',
    lat: 11.0347,
    long: 77.0396,
    phone: '+91 422 432 3800',
    emergencyHotline: '10578 / +91 422 262 7788',
    icuBedsAvailable: 20,
    ambulanceUnits: 8,
    distanceKm: '3.1'
  },
  {
    id: 'HOSP-004',
    name: 'Madurai Government Rajaji Hospital (GRH)',
    tamilName: 'மதுரை அரசு இராஜாஜி மருத்துவமனை',
    addressText: 'Panagal Road, Goripalayam, Madurai - 625020',
    lat: 9.9272,
    long: 78.1348,
    phone: '+91 452 253 2535',
    emergencyHotline: '108 / +91 452 253 2530',
    icuBedsAvailable: 28,
    ambulanceUnits: 10,
    distanceKm: '2.0'
  }
];
